#!/bin/sh
# author: xionghao 00121577
# date:   2008-08-07
export LANG="en_US.UTF-8"
export COLUMNS=256
if [ "$1" = "" ]; then
        echo "parameter error"
	exit 2
else
        DEVICE=$1
fi

PID=`fuser $DEVICE`

if test $PID; then
	echo $PID
	exit 1
else
	echo "no user"
	exit 0
fi
